// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Pool,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.265800,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=12,HLS_SYN_FF=3860,HLS_SYN_LUT=5077}" *)

module Pool (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 76'd1;
parameter    ap_ST_fsm_state2 = 76'd2;
parameter    ap_ST_fsm_state3 = 76'd4;
parameter    ap_ST_fsm_state4 = 76'd8;
parameter    ap_ST_fsm_state5 = 76'd16;
parameter    ap_ST_fsm_state6 = 76'd32;
parameter    ap_ST_fsm_state7 = 76'd64;
parameter    ap_ST_fsm_state8 = 76'd128;
parameter    ap_ST_fsm_state9 = 76'd256;
parameter    ap_ST_fsm_state10 = 76'd512;
parameter    ap_ST_fsm_state11 = 76'd1024;
parameter    ap_ST_fsm_state12 = 76'd2048;
parameter    ap_ST_fsm_state13 = 76'd4096;
parameter    ap_ST_fsm_state14 = 76'd8192;
parameter    ap_ST_fsm_state15 = 76'd16384;
parameter    ap_ST_fsm_state16 = 76'd32768;
parameter    ap_ST_fsm_state17 = 76'd65536;
parameter    ap_ST_fsm_state18 = 76'd131072;
parameter    ap_ST_fsm_state19 = 76'd262144;
parameter    ap_ST_fsm_state20 = 76'd524288;
parameter    ap_ST_fsm_state21 = 76'd1048576;
parameter    ap_ST_fsm_state22 = 76'd2097152;
parameter    ap_ST_fsm_state23 = 76'd4194304;
parameter    ap_ST_fsm_state24 = 76'd8388608;
parameter    ap_ST_fsm_state25 = 76'd16777216;
parameter    ap_ST_fsm_state26 = 76'd33554432;
parameter    ap_ST_fsm_state27 = 76'd67108864;
parameter    ap_ST_fsm_state28 = 76'd134217728;
parameter    ap_ST_fsm_state29 = 76'd268435456;
parameter    ap_ST_fsm_state30 = 76'd536870912;
parameter    ap_ST_fsm_state31 = 76'd1073741824;
parameter    ap_ST_fsm_state32 = 76'd2147483648;
parameter    ap_ST_fsm_state33 = 76'd4294967296;
parameter    ap_ST_fsm_state34 = 76'd8589934592;
parameter    ap_ST_fsm_state35 = 76'd17179869184;
parameter    ap_ST_fsm_state36 = 76'd34359738368;
parameter    ap_ST_fsm_state37 = 76'd68719476736;
parameter    ap_ST_fsm_state38 = 76'd137438953472;
parameter    ap_ST_fsm_state39 = 76'd274877906944;
parameter    ap_ST_fsm_state40 = 76'd549755813888;
parameter    ap_ST_fsm_state41 = 76'd1099511627776;
parameter    ap_ST_fsm_state42 = 76'd2199023255552;
parameter    ap_ST_fsm_state43 = 76'd4398046511104;
parameter    ap_ST_fsm_state44 = 76'd8796093022208;
parameter    ap_ST_fsm_state45 = 76'd17592186044416;
parameter    ap_ST_fsm_state46 = 76'd35184372088832;
parameter    ap_ST_fsm_state47 = 76'd70368744177664;
parameter    ap_ST_fsm_state48 = 76'd140737488355328;
parameter    ap_ST_fsm_state49 = 76'd281474976710656;
parameter    ap_ST_fsm_state50 = 76'd562949953421312;
parameter    ap_ST_fsm_state51 = 76'd1125899906842624;
parameter    ap_ST_fsm_state52 = 76'd2251799813685248;
parameter    ap_ST_fsm_state53 = 76'd4503599627370496;
parameter    ap_ST_fsm_state54 = 76'd9007199254740992;
parameter    ap_ST_fsm_state55 = 76'd18014398509481984;
parameter    ap_ST_fsm_state56 = 76'd36028797018963968;
parameter    ap_ST_fsm_state57 = 76'd72057594037927936;
parameter    ap_ST_fsm_state58 = 76'd144115188075855872;
parameter    ap_ST_fsm_state59 = 76'd288230376151711744;
parameter    ap_ST_fsm_state60 = 76'd576460752303423488;
parameter    ap_ST_fsm_state61 = 76'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 76'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 76'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 76'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 76'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 76'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 76'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 76'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 76'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 76'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 76'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 76'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 76'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 76'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 76'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 76'd37778931862957161709568;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [75:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] CHin_V;
wire   [15:0] Hin_V;
wire   [15:0] Win_V;
wire   [7:0] Kx_V;
wire   [7:0] Ky_V;
wire   [1:0] mode_V;
wire   [31:0] feature_in;
wire   [31:0] feature_out;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state39;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state28;
reg   [1:0] mode_V_read_reg_909;
wire    ap_CS_fsm_state35;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state70;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state71;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state76;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [31:0] gmem_ARADDR;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [7:0] Ky_V_read_reg_915;
reg   [7:0] Kx_V_read_reg_920;
reg   [15:0] Win_V_read_reg_925;
reg   [15:0] CHin_V_read_reg_936;
reg   [29:0] tmp_3_reg_943;
reg   [29:0] tmp_5_reg_948;
wire   [15:0] lhs_V_fu_404_p1;
reg   [15:0] lhs_V_reg_953;
wire   [15:0] rhs_V_fu_414_p1;
reg   [15:0] rhs_V_reg_960;
wire   [15:0] r_V_16_fu_424_p2;
reg   [15:0] r_V_16_reg_967;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire   [48:0] tmp_31_cast_fu_432_p1;
reg   [48:0] tmp_31_cast_reg_977;
wire    ap_CS_fsm_state20;
wire   [47:0] tmp_32_cast_fu_435_p1;
reg   [47:0] tmp_32_cast_reg_982;
wire   [15:0] grp_fu_408_p2;
reg   [15:0] r_V_15_reg_989;
wire   [15:0] grp_fu_418_p2;
reg   [15:0] tmp_4_reg_994;
wire   [0:0] tmp_6_fu_438_p2;
reg   [0:0] tmp_6_reg_999;
wire   [31:0] rhs_V_1_fu_448_p1;
reg   [31:0] rhs_V_1_reg_1003;
wire   [47:0] rhs_V_2_fu_451_p1;
reg   [47:0] rhs_V_2_reg_1012;
wire   [31:0] grp_fu_376_p1;
reg   [31:0] tmp_1_reg_1017;
wire   [31:0] rhs_V_1_cast_fu_454_p1;
reg   [31:0] rhs_V_1_cast_reg_1022;
wire   [47:0] rhs_V_2_cast_fu_458_p1;
reg   [47:0] rhs_V_2_cast_reg_1027;
wire   [31:0] p_sum_fu_475_p3;
reg   [31:0] p_sum_reg_1032;
wire   [31:0] i_op_assign_17_cast6_fu_483_p1;
reg   [31:0] i_op_assign_17_cast6_reg_1037;
wire    ap_CS_fsm_state21;
wire   [15:0] c_fu_492_p2;
reg   [15:0] c_reg_1045;
wire   [47:0] rhs_V_7_cast_fu_498_p1;
reg   [47:0] rhs_V_7_cast_reg_1050;
wire   [0:0] exitcond1_fu_487_p2;
wire   [31:0] next_mul1_fu_502_p2;
reg   [31:0] next_mul1_reg_1057;
wire    ap_CS_fsm_state22;
wire   [15:0] next_mul2_fu_507_p2;
reg   [15:0] next_mul2_reg_1062;
wire   [15:0] i_fu_517_p2;
reg   [15:0] i_reg_1070;
wire   [47:0] r_V_1_fu_527_p2;
reg   [47:0] r_V_1_reg_1075;
wire   [0:0] exitcond2_fu_512_p2;
wire   [15:0] next_mul9_fu_532_p2;
reg   [15:0] next_mul9_reg_1080;
wire    ap_CS_fsm_state23;
wire   [31:0] next_mul_fu_537_p2;
reg   [31:0] next_mul_reg_1085;
wire   [15:0] j_fu_547_p2;
reg   [15:0] j_reg_1093;
wire   [7:0] ii_fu_558_p2;
reg   [7:0] ii_reg_1101;
wire    ap_CS_fsm_state24;
wire  signed [31:0] r_V_fu_883_p2;
reg  signed [31:0] r_V_reg_1106;
wire   [0:0] exitcond3_fu_553_p2;
wire   [47:0] r_V_2_fu_581_p2;
reg   [47:0] r_V_2_reg_1111;
wire    ap_CS_fsm_state25;
wire   [7:0] jj_fu_591_p2;
reg   [7:0] jj_reg_1121;
wire    ap_CS_fsm_state26;
wire   [15:0] w_V_fu_601_p2;
reg  signed [15:0] w_V_reg_1126;
wire   [0:0] exitcond4_fu_586_p2;
reg   [31:0] gmem_addr_3_reg_1133;
wire    ap_CS_fsm_state27;
reg   [31:0] gmem_addr_2_reg_1139;
reg   [31:0] gmem_addr_3_read_reg_1145;
reg    ap_block_state35;
reg   [31:0] gmem_addr_2_read_reg_1152;
wire   [0:0] grp_fu_379_p2;
reg   [0:0] tmp_26_reg_1159;
wire    ap_CS_fsm_state36;
reg   [0:0] tmp_17_reg_1164;
wire   [31:0] sum_3_feature_in_loa_fu_733_p3;
wire    ap_CS_fsm_state37;
wire   [31:0] feature_in_load_1_su_fu_822_p3;
reg   [31:0] gmem_addr_1_reg_1179;
wire    ap_CS_fsm_state38;
reg   [31:0] gmem_addr_1_read_reg_1185;
wire   [31:0] grp_fu_366_p2;
reg   [31:0] sum_2_reg_1190;
wire    ap_CS_fsm_state51;
wire   [31:0] grp_fu_371_p2;
wire    ap_CS_fsm_state68;
wire   [47:0] tmp_9_fu_860_p2;
reg   [47:0] tmp_9_reg_1200;
reg   [31:0] gmem_addr_reg_1205;
wire    ap_CS_fsm_state69;
reg   [15:0] op_assign_8_reg_214;
reg   [15:0] i_op_assign_s_reg_225;
wire   [0:0] exitcond_fu_542_p2;
reg   [15:0] phi_mul1_reg_236;
reg   [31:0] r_V_4_reg_248;
reg   [15:0] i_op_assign_1_reg_259;
reg   [31:0] r_V_10_reg_270;
reg   [15:0] phi_mul8_reg_282;
reg   [31:0] i_op_assign_reg_294;
reg   [7:0] i_op_assign_2_reg_304;
reg   [31:0] sum_3_reg_315;
wire    ap_CS_fsm_state53;
reg   [7:0] i_op_assign_3_reg_327;
reg   [31:0] sum_3_be_reg_338;
wire    ap_CS_fsm_state52;
reg   [31:0] sum_5_reg_354;
wire  signed [63:0] feature_in2_sum_cast_fu_619_p1;
wire  signed [63:0] feature_in2_sum5_cas_fu_641_p1;
wire  signed [63:0] feature_in2_sum6_cas_fu_841_p1;
wire   [63:0] feature_out4_sum_cas_fu_873_p1;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_block_state28_io;
reg    ap_reg_ioackin_gmem_AWREADY;
reg    ap_sig_ioackin_gmem_AWREADY;
reg    ap_reg_ioackin_gmem_WREADY;
reg    ap_sig_ioackin_gmem_WREADY;
wire    ap_CS_fsm_state47;
wire   [31:0] grp_fu_376_p0;
reg   [31:0] grp_fu_379_p1;
wire   [7:0] grp_fu_408_p1;
wire   [7:0] grp_fu_418_p1;
wire   [7:0] r_V_16_fu_424_p0;
wire   [7:0] r_V_16_fu_424_p1;
wire   [0:0] tmp_7_fu_443_p2;
wire   [0:0] tmp_2_fu_469_p2;
wire   [31:0] sum_fu_461_p3;
wire   [31:0] r_V_1_fu_527_p0;
wire   [15:0] r_V_1_fu_527_p1;
wire   [15:0] tmp_8_fu_564_p1;
wire  signed [15:0] h_V_fu_568_p2;
wire  signed [31:0] r_V_2_fu_581_p0;
wire   [15:0] r_V_2_fu_581_p1;
wire   [15:0] tmp_10_fu_597_p1;
wire  signed [47:0] grp_fu_888_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_14_fu_610_p2;
wire   [47:0] feature_in2_sum_fu_614_p2;
wire  signed [47:0] grp_fu_895_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_11_fu_632_p2;
wire   [47:0] feature_in2_sum5_fu_636_p2;
wire   [31:0] sum_3_to_int7_fu_651_p1;
wire   [31:0] feature_in_load_2_to_fu_669_p1;
wire   [7:0] tmp_19_fu_655_p4;
wire   [22:0] tmp_20_fu_665_p1;
wire   [0:0] notrhs_fu_692_p2;
wire   [0:0] notlhs_fu_686_p2;
wire   [7:0] tmp_21_fu_672_p4;
wire   [22:0] tmp_22_fu_682_p1;
wire   [0:0] notrhs9_fu_710_p2;
wire   [0:0] notlhs8_fu_704_p2;
wire   [0:0] tmp_23_fu_698_p2;
wire   [0:0] tmp_24_fu_716_p2;
wire   [0:0] tmp_25_fu_722_p2;
wire   [0:0] tmp_27_fu_728_p2;
wire   [31:0] sum_3_to_int_fu_740_p1;
wire   [31:0] feature_in_load_1_to_fu_758_p1;
wire   [7:0] tmp_fu_744_p4;
wire   [22:0] tmp_11_fu_754_p1;
wire   [0:0] notrhs1_fu_781_p2;
wire   [0:0] notlhs1_fu_775_p2;
wire   [7:0] tmp_12_fu_761_p4;
wire   [22:0] tmp_13_fu_771_p1;
wire   [0:0] notrhs2_fu_799_p2;
wire   [0:0] notlhs2_fu_793_p2;
wire   [0:0] tmp_14_fu_787_p2;
wire   [0:0] tmp_15_fu_805_p2;
wire   [0:0] tmp_16_fu_811_p2;
wire   [0:0] tmp_18_fu_817_p2;
wire  signed [47:0] grp_fu_902_p3;
(* use_dsp48 = "no" *) wire   [47:0] r_V_7_fu_832_p2;
wire   [47:0] feature_in2_sum6_fu_836_p2;
wire   [31:0] tmp1_fu_851_p2;
wire   [47:0] tmp1_cast_fu_856_p1;
wire   [48:0] tmp_17_cast_cast_fu_865_p1;
wire   [48:0] feature_out4_sum_fu_868_p2;
wire   [15:0] r_V_fu_883_p1;
wire   [15:0] grp_fu_888_p0;
wire   [15:0] grp_fu_895_p0;
wire   [15:0] grp_fu_902_p0;
reg    grp_fu_408_ap_start;
wire    grp_fu_408_ap_done;
reg    grp_fu_418_ap_start;
wire    grp_fu_418_ap_done;
reg   [75:0] ap_NS_fsm;
wire   [15:0] grp_fu_408_p10;
wire   [15:0] grp_fu_418_p10;
wire   [47:0] r_V_1_fu_527_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 76'd1;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem_WREADY = 1'b0;
end

Pool_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
Pool_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .CHin_V(CHin_V),
    .Hin_V(Hin_V),
    .Win_V(Win_V),
    .Kx_V(Kx_V),
    .Ky_V(Ky_V),
    .mode_V(mode_V),
    .feature_in(feature_in),
    .feature_out(feature_out)
);

Pool_gmem_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
Pool_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_reg_1205),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(sum_5_reg_354),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

Pool_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_fadd_32ns_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(sum_3_reg_315),
    .din1(gmem_addr_1_read_reg_1185),
    .ce(1'b1),
    .dout(grp_fu_366_p2)
);

Pool_fdiv_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_fdiv_32ns_32cud_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(i_op_assign_reg_294),
    .din1(tmp_1_reg_1017),
    .ce(1'b1),
    .dout(grp_fu_371_p2)
);

Pool_sitofp_32ns_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Pool_sitofp_32ns_dEe_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_376_p0),
    .ce(1'b1),
    .dout(grp_fu_376_p1)
);

Pool_fcmp_32ns_32eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
Pool_fcmp_32ns_32eOg_U4(
    .din0(sum_3_reg_315),
    .din1(grp_fu_379_p1),
    .opcode(5'd2),
    .dout(grp_fu_379_p2)
);

Pool_udiv_16ns_8nfYi #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
Pool_udiv_16ns_8nfYi_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_408_ap_start),
    .done(grp_fu_408_ap_done),
    .din0(Win_V),
    .din1(grp_fu_408_p1),
    .ce(1'b1),
    .dout(grp_fu_408_p2)
);

Pool_udiv_16ns_8nfYi #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
Pool_udiv_16ns_8nfYi_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_418_ap_start),
    .done(grp_fu_418_ap_done),
    .din0(Hin_V),
    .din1(grp_fu_418_p1),
    .ce(1'b1),
    .dout(grp_fu_418_p2)
);

Pool_mul_mul_16s_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Pool_mul_mul_16s_g8j_U7(
    .din0(h_V_fu_568_p2),
    .din1(r_V_fu_883_p1),
    .dout(r_V_fu_883_p2)
);

Pool_mac_muladd_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_1hbi_U8(
    .din0(grp_fu_888_p0),
    .din1(w_V_reg_1126),
    .din2(r_V_2_reg_1111),
    .dout(grp_fu_888_p3)
);

Pool_mac_muladd_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_1hbi_U9(
    .din0(grp_fu_895_p0),
    .din1(w_V_reg_1126),
    .din2(r_V_2_reg_1111),
    .dout(grp_fu_895_p3)
);

Pool_mac_muladd_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Pool_mac_muladd_1hbi_U10(
    .din0(grp_fu_902_p0),
    .din1(w_V_reg_1126),
    .din2(r_V_2_reg_1111),
    .dout(grp_fu_902_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_state28_io) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd2)) | ((1'b0 == ap_block_state28_io) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd1)) | ((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state39)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b0;
        end else if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd1)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state39)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state70)) begin
            if ((ap_sig_ioackin_gmem_AWREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b0;
            end else if ((gmem_AWREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state71)) begin
            if ((ap_sig_ioackin_gmem_WREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b0;
            end else if ((gmem_WREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        i_op_assign_1_reg_259 <= 16'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        i_op_assign_1_reg_259 <= j_reg_1093;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_542_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        i_op_assign_2_reg_304 <= 8'd0;
    end else if (((exitcond4_fu_586_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        i_op_assign_2_reg_304 <= ii_reg_1101;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        i_op_assign_3_reg_327 <= jj_reg_1121;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        i_op_assign_3_reg_327 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_542_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        i_op_assign_reg_294 <= p_sum_reg_1032;
    end else if (((exitcond4_fu_586_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        i_op_assign_reg_294 <= sum_3_reg_315;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        i_op_assign_s_reg_225 <= i_reg_1070;
    end else if (((exitcond1_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        i_op_assign_s_reg_225 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        op_assign_8_reg_214 <= c_reg_1045;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        op_assign_8_reg_214 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        phi_mul1_reg_236 <= next_mul2_reg_1062;
    end else if (((exitcond1_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        phi_mul1_reg_236 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        phi_mul8_reg_282 <= 16'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        phi_mul8_reg_282 <= next_mul9_reg_1080;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        r_V_10_reg_270 <= 32'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        r_V_10_reg_270 <= next_mul_reg_1085;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        r_V_4_reg_248 <= next_mul1_reg_1057;
    end else if (((exitcond1_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        r_V_4_reg_248 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) & (mode_V_read_reg_909 == 2'd2))) begin
        sum_3_be_reg_338 <= sum_3_feature_in_loa_fu_733_p3;
    end else if (((1'b1 == ap_CS_fsm_state37) & (mode_V_read_reg_909 == 2'd1))) begin
        sum_3_be_reg_338 <= feature_in_load_1_su_fu_822_p3;
    end else if (((exitcond4_fu_586_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26) & (mode_V_read_reg_909 == 2'd3))) begin
        sum_3_be_reg_338 <= sum_3_reg_315;
    end else if ((1'b1 == ap_CS_fsm_state52)) begin
        sum_3_be_reg_338 <= sum_2_reg_1190;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        sum_3_reg_315 <= sum_3_be_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        sum_3_reg_315 <= i_op_assign_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_553_p2 == 1'd1) & (tmp_6_reg_999 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        sum_5_reg_354 <= i_op_assign_reg_294;
    end else if (((tmp_6_reg_999 == 1'd1) & (1'b1 == ap_CS_fsm_state68))) begin
        sum_5_reg_354 <= grp_fu_371_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        CHin_V_read_reg_936 <= CHin_V;
        Kx_V_read_reg_920 <= Kx_V;
        Ky_V_read_reg_915 <= Ky_V;
        Win_V_read_reg_925 <= Win_V;
        lhs_V_reg_953[7 : 0] <= lhs_V_fu_404_p1[7 : 0];
        mode_V_read_reg_909 <= mode_V;
        rhs_V_reg_960[7 : 0] <= rhs_V_fu_414_p1[7 : 0];
        tmp_3_reg_943 <= {{feature_out[31:2]}};
        tmp_5_reg_948 <= {{feature_in[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        c_reg_1045 <= c_fu_492_p2;
        i_op_assign_17_cast6_reg_1037[15 : 0] <= i_op_assign_17_cast6_fu_483_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state46))) begin
        gmem_addr_1_read_reg_1185 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        gmem_addr_1_reg_1179 <= feature_in2_sum6_cas_fu_841_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1))) & (1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd1))) begin
        gmem_addr_2_read_reg_1152 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state27) & (mode_V_read_reg_909 == 2'd1))) begin
        gmem_addr_2_reg_1139 <= feature_in2_sum5_cas_fu_641_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1))) & (1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd2))) begin
        gmem_addr_3_read_reg_1145 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state27) & (mode_V_read_reg_909 == 2'd2))) begin
        gmem_addr_3_reg_1133 <= feature_in2_sum_cast_fu_619_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        gmem_addr_reg_1205 <= feature_out4_sum_cas_fu_873_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        i_reg_1070 <= i_fu_517_p2;
        next_mul1_reg_1057 <= next_mul1_fu_502_p2;
        next_mul2_reg_1062 <= next_mul2_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        ii_reg_1101 <= ii_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        j_reg_1093 <= j_fu_547_p2;
        next_mul9_reg_1080 <= next_mul9_fu_532_p2;
        next_mul_reg_1085 <= next_mul_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        jj_reg_1121 <= jj_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        p_sum_reg_1032[5 : 2] <= p_sum_fu_475_p3[5 : 2];
p_sum_reg_1032[7] <= p_sum_fu_475_p3[7];
p_sum_reg_1032[9] <= p_sum_fu_475_p3[9];
p_sum_reg_1032[13] <= p_sum_fu_475_p3[13];
p_sum_reg_1032[16 : 15] <= p_sum_fu_475_p3[16 : 15];
p_sum_reg_1032[21 : 20] <= p_sum_fu_475_p3[21 : 20];
p_sum_reg_1032[25 : 23] <= p_sum_fu_475_p3[25 : 23];
p_sum_reg_1032[28 : 27] <= p_sum_fu_475_p3[28 : 27];
p_sum_reg_1032[31 : 30] <= p_sum_fu_475_p3[31 : 30];
        r_V_15_reg_989 <= grp_fu_408_p2;
        rhs_V_1_cast_reg_1022[15 : 0] <= rhs_V_1_cast_fu_454_p1[15 : 0];
        rhs_V_1_reg_1003[15 : 0] <= rhs_V_1_fu_448_p1[15 : 0];
        rhs_V_2_cast_reg_1027[15 : 0] <= rhs_V_2_cast_fu_458_p1[15 : 0];
        rhs_V_2_reg_1012[15 : 0] <= rhs_V_2_fu_451_p1[15 : 0];
        tmp_1_reg_1017 <= grp_fu_376_p1;
        tmp_31_cast_reg_977[29 : 0] <= tmp_31_cast_fu_432_p1[29 : 0];
        tmp_32_cast_reg_982[29 : 0] <= tmp_32_cast_fu_435_p1[29 : 0];
        tmp_4_reg_994 <= grp_fu_418_p2;
        tmp_6_reg_999 <= tmp_6_fu_438_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        r_V_16_reg_967 <= r_V_16_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        r_V_1_reg_1075 <= r_V_1_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        r_V_2_reg_1111 <= r_V_2_fu_581_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_553_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        r_V_reg_1106 <= r_V_fu_883_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        rhs_V_7_cast_reg_1050[15 : 0] <= rhs_V_7_cast_fu_498_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        sum_2_reg_1190 <= grp_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state36) & (mode_V_read_reg_909 == 2'd1))) begin
        tmp_17_reg_1164 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state36) & (mode_V_read_reg_909 == 2'd2))) begin
        tmp_26_reg_1159 <= grp_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        tmp_9_reg_1200 <= tmp_9_fu_860_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_586_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        w_V_reg_1126 <= w_V_fu_601_p2;
    end
end

always @ (*) begin
    if (((exitcond1_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_ARREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_AWREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_WREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_ARREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state39)) begin
            gmem_ARADDR = gmem_addr_1_reg_1179;
        end else if (((1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd1))) begin
            gmem_ARADDR = gmem_addr_2_reg_1139;
        end else if (((1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd2))) begin
            gmem_ARADDR = gmem_addr_3_reg_1133;
        end else begin
            gmem_ARADDR = 'bx;
        end
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd2)) | ((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd1)) | ((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state39)))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_gmem_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state70))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((~(((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1))) & (1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd2)) | (~(((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1))) & (1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd1)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state46)))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_gmem_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state71))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | ((1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd2)) | ((1'b1 == ap_CS_fsm_state28) & (mode_V_read_reg_909 == 2'd1)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | ((1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd2)) | ((1'b1 == ap_CS_fsm_state35) & (mode_V_read_reg_909 == 2'd1)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        if ((mode_V_read_reg_909 == 2'd1)) begin
            grp_fu_379_p1 = gmem_addr_2_read_reg_1152;
        end else if ((mode_V_read_reg_909 == 2'd2)) begin
            grp_fu_379_p1 = gmem_addr_3_read_reg_1145;
        end else begin
            grp_fu_379_p1 = 'bx;
        end
    end else begin
        grp_fu_379_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_408_ap_start = 1'b1;
    end else begin
        grp_fu_408_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_418_ap_start = 1'b1;
    end else begin
        grp_fu_418_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((exitcond1_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((exitcond2_fu_512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((exitcond_fu_542_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((exitcond3_fu_553_p2 == 1'd1) & (tmp_6_reg_999 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state68;
            end else if (((exitcond3_fu_553_p2 == 1'd1) & (tmp_6_reg_999 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((exitcond4_fu_586_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((exitcond4_fu_586_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26) & (mode_V_read_reg_909 == 2'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else if (((exitcond4_fu_586_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26) & (mode_V_read_reg_909 == 2'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b0 == ap_block_state28_io) & (1'b1 == ap_CS_fsm_state28) & ((mode_V_read_reg_909 == 2'd2) | (mode_V_read_reg_909 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if ((~(((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1))) & (1'b1 == ap_CS_fsm_state35) & ((mode_V_read_reg_909 == 2'd2) | (mode_V_read_reg_909 == 2'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state46))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state70))) begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end
        end
        ap_ST_fsm_state71 : begin
            if (((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state71))) begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

always @ (*) begin
    ap_block_state28_io = (((ap_sig_ioackin_gmem_ARREADY == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((ap_sig_ioackin_gmem_ARREADY == 1'b0) & (mode_V_read_reg_909 == 2'd1)));
end

always @ (*) begin
    ap_block_state35 = (((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd2)) | ((gmem_RVALID == 1'b0) & (mode_V_read_reg_909 == 2'd1)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign c_fu_492_p2 = (op_assign_8_reg_214 + 16'd1);

assign exitcond1_fu_487_p2 = ((op_assign_8_reg_214 == CHin_V_read_reg_936) ? 1'b1 : 1'b0);

assign exitcond2_fu_512_p2 = ((i_op_assign_s_reg_225 == tmp_4_reg_994) ? 1'b1 : 1'b0);

assign exitcond3_fu_553_p2 = ((i_op_assign_2_reg_304 == Ky_V_read_reg_915) ? 1'b1 : 1'b0);

assign exitcond4_fu_586_p2 = ((i_op_assign_3_reg_327 == Kx_V_read_reg_920) ? 1'b1 : 1'b0);

assign exitcond_fu_542_p2 = ((i_op_assign_1_reg_259 == r_V_15_reg_989) ? 1'b1 : 1'b0);

assign feature_in2_sum5_cas_fu_641_p1 = $signed(feature_in2_sum5_fu_636_p2);

assign feature_in2_sum5_fu_636_p2 = (tmp_32_cast_reg_982 + r_V_11_fu_632_p2);

assign feature_in2_sum6_cas_fu_841_p1 = $signed(feature_in2_sum6_fu_836_p2);

assign feature_in2_sum6_fu_836_p2 = (r_V_7_fu_832_p2 + tmp_32_cast_reg_982);

assign feature_in2_sum_cast_fu_619_p1 = $signed(feature_in2_sum_fu_614_p2);

assign feature_in2_sum_fu_614_p2 = (tmp_32_cast_reg_982 + r_V_14_fu_610_p2);

assign feature_in_load_1_su_fu_822_p3 = ((tmp_18_fu_817_p2[0:0] === 1'b1) ? gmem_addr_2_read_reg_1152 : sum_3_reg_315);

assign feature_in_load_1_to_fu_758_p1 = gmem_addr_2_read_reg_1152;

assign feature_in_load_2_to_fu_669_p1 = gmem_addr_3_read_reg_1145;

assign feature_out4_sum_cas_fu_873_p1 = feature_out4_sum_fu_868_p2;

assign feature_out4_sum_fu_868_p2 = (tmp_17_cast_cast_fu_865_p1 + tmp_31_cast_reg_977);

assign grp_fu_376_p0 = r_V_16_reg_967;

assign grp_fu_408_p1 = grp_fu_408_p10;

assign grp_fu_408_p10 = Kx_V;

assign grp_fu_418_p1 = grp_fu_418_p10;

assign grp_fu_418_p10 = Ky_V;

assign grp_fu_888_p0 = rhs_V_1_reg_1003;

assign grp_fu_895_p0 = rhs_V_1_reg_1003;

assign grp_fu_902_p0 = rhs_V_1_reg_1003;

assign h_V_fu_568_p2 = (tmp_8_fu_564_p1 + phi_mul1_reg_236);

assign i_fu_517_p2 = (i_op_assign_s_reg_225 + 16'd1);

assign i_op_assign_17_cast6_fu_483_p1 = op_assign_8_reg_214;

assign ii_fu_558_p2 = (i_op_assign_2_reg_304 + 8'd1);

assign j_fu_547_p2 = (i_op_assign_1_reg_259 + 16'd1);

assign jj_fu_591_p2 = (i_op_assign_3_reg_327 + 8'd1);

assign lhs_V_fu_404_p1 = Kx_V;

assign next_mul1_fu_502_p2 = (r_V_4_reg_248 + rhs_V_1_cast_reg_1022);

assign next_mul2_fu_507_p2 = (phi_mul1_reg_236 + rhs_V_reg_960);

assign next_mul9_fu_532_p2 = (phi_mul8_reg_282 + lhs_V_reg_953);

assign next_mul_fu_537_p2 = (r_V_10_reg_270 + rhs_V_1_reg_1003);

assign notlhs1_fu_775_p2 = ((tmp_fu_744_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs2_fu_793_p2 = ((tmp_12_fu_761_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs8_fu_704_p2 = ((tmp_21_fu_672_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notlhs_fu_686_p2 = ((tmp_19_fu_655_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs1_fu_781_p2 = ((tmp_11_fu_754_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs2_fu_799_p2 = ((tmp_13_fu_771_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs9_fu_710_p2 = ((tmp_22_fu_682_p1 == 23'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_692_p2 = ((tmp_20_fu_665_p1 == 23'd0) ? 1'b1 : 1'b0);

assign p_sum_fu_475_p3 = ((tmp_2_fu_469_p2[0:0] === 1'b1) ? sum_fu_461_p3 : 32'd3685851836);

assign r_V_11_fu_632_p2 = ($signed(rhs_V_7_cast_reg_1050) + $signed(grp_fu_895_p3));

assign r_V_14_fu_610_p2 = ($signed(rhs_V_7_cast_reg_1050) + $signed(grp_fu_888_p3));

assign r_V_16_fu_424_p0 = rhs_V_reg_960;

assign r_V_16_fu_424_p1 = lhs_V_reg_953;

assign r_V_16_fu_424_p2 = (r_V_16_fu_424_p0 * r_V_16_fu_424_p1);

assign r_V_1_fu_527_p0 = r_V_1_fu_527_p00;

assign r_V_1_fu_527_p00 = r_V_4_reg_248;

assign r_V_1_fu_527_p1 = rhs_V_2_cast_reg_1027;

assign r_V_1_fu_527_p2 = (r_V_1_fu_527_p0 * r_V_1_fu_527_p1);

assign r_V_2_fu_581_p0 = r_V_reg_1106;

assign r_V_2_fu_581_p1 = rhs_V_2_reg_1012;

assign r_V_2_fu_581_p2 = ($signed(r_V_2_fu_581_p0) * $signed({{1'b0}, {r_V_2_fu_581_p1}}));

assign r_V_7_fu_832_p2 = ($signed(rhs_V_7_cast_reg_1050) + $signed(grp_fu_902_p3));

assign r_V_fu_883_p1 = rhs_V_1_reg_1003;

assign rhs_V_1_cast_fu_454_p1 = grp_fu_408_p2;

assign rhs_V_1_fu_448_p1 = CHin_V_read_reg_936;

assign rhs_V_2_cast_fu_458_p1 = CHin_V_read_reg_936;

assign rhs_V_2_fu_451_p1 = Win_V_read_reg_925;

assign rhs_V_7_cast_fu_498_p1 = op_assign_8_reg_214;

assign rhs_V_fu_414_p1 = Ky_V;

assign sum_3_feature_in_loa_fu_733_p3 = ((tmp_27_fu_728_p2[0:0] === 1'b1) ? sum_3_reg_315 : gmem_addr_3_read_reg_1145);

assign sum_3_to_int7_fu_651_p1 = sum_3_reg_315;

assign sum_3_to_int_fu_740_p1 = sum_3_reg_315;

assign sum_fu_461_p3 = ((tmp_6_fu_438_p2[0:0] === 1'b1) ? 32'd0 : 32'd1538368188);

assign tmp1_cast_fu_856_p1 = tmp1_fu_851_p2;

assign tmp1_fu_851_p2 = (i_op_assign_17_cast6_reg_1037 + r_V_10_reg_270);

assign tmp_10_fu_597_p1 = i_op_assign_3_reg_327;

assign tmp_11_fu_754_p1 = sum_3_to_int_fu_740_p1[22:0];

assign tmp_12_fu_761_p4 = {{feature_in_load_1_to_fu_758_p1[30:23]}};

assign tmp_13_fu_771_p1 = feature_in_load_1_to_fu_758_p1[22:0];

assign tmp_14_fu_787_p2 = (notrhs1_fu_781_p2 | notlhs1_fu_775_p2);

assign tmp_15_fu_805_p2 = (notrhs2_fu_799_p2 | notlhs2_fu_793_p2);

assign tmp_16_fu_811_p2 = (tmp_15_fu_805_p2 & tmp_14_fu_787_p2);

assign tmp_17_cast_cast_fu_865_p1 = tmp_9_reg_1200;

assign tmp_18_fu_817_p2 = (tmp_17_reg_1164 & tmp_16_fu_811_p2);

assign tmp_19_fu_655_p4 = {{sum_3_to_int7_fu_651_p1[30:23]}};

assign tmp_20_fu_665_p1 = sum_3_to_int7_fu_651_p1[22:0];

assign tmp_21_fu_672_p4 = {{feature_in_load_2_to_fu_669_p1[30:23]}};

assign tmp_22_fu_682_p1 = feature_in_load_2_to_fu_669_p1[22:0];

assign tmp_23_fu_698_p2 = (notrhs_fu_692_p2 | notlhs_fu_686_p2);

assign tmp_24_fu_716_p2 = (notrhs9_fu_710_p2 | notlhs8_fu_704_p2);

assign tmp_25_fu_722_p2 = (tmp_24_fu_716_p2 & tmp_23_fu_698_p2);

assign tmp_27_fu_728_p2 = (tmp_26_reg_1159 & tmp_25_fu_722_p2);

assign tmp_2_fu_469_p2 = (tmp_7_fu_443_p2 | tmp_6_fu_438_p2);

assign tmp_31_cast_fu_432_p1 = tmp_3_reg_943;

assign tmp_32_cast_fu_435_p1 = tmp_5_reg_948;

assign tmp_6_fu_438_p2 = ((mode_V_read_reg_909 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_7_fu_443_p2 = ((mode_V_read_reg_909 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_8_fu_564_p1 = i_op_assign_2_reg_304;

assign tmp_9_fu_860_p2 = (r_V_1_reg_1075 + tmp1_cast_fu_856_p1);

assign tmp_fu_744_p4 = {{sum_3_to_int_fu_740_p1[30:23]}};

assign w_V_fu_601_p2 = (phi_mul8_reg_282 + tmp_10_fu_597_p1);

always @ (posedge ap_clk) begin
    lhs_V_reg_953[15:8] <= 8'b00000000;
    rhs_V_reg_960[15:8] <= 8'b00000000;
    tmp_31_cast_reg_977[48:30] <= 19'b0000000000000000000;
    tmp_32_cast_reg_982[47:30] <= 18'b000000000000000000;
    rhs_V_1_reg_1003[31:16] <= 16'b0000000000000000;
    rhs_V_2_reg_1012[47:16] <= 32'b00000000000000000000000000000000;
    rhs_V_1_cast_reg_1022[31:16] <= 16'b0000000000000000;
    rhs_V_2_cast_reg_1027[47:16] <= 32'b00000000000000000000000000000000;
    p_sum_reg_1032[1:0] <= 2'b00;
    p_sum_reg_1032[6:6] <= 1'b0;
    p_sum_reg_1032[8:8] <= 1'b0;
    p_sum_reg_1032[12:10] <= 3'b000;
    p_sum_reg_1032[14:14] <= 1'b0;
    p_sum_reg_1032[19:17] <= 3'b000;
    p_sum_reg_1032[22:22] <= 1'b0;
    p_sum_reg_1032[26:26] <= 1'b0;
    p_sum_reg_1032[29] <= 1'b0;
    i_op_assign_17_cast6_reg_1037[31:16] <= 16'b0000000000000000;
    rhs_V_7_cast_reg_1050[47:16] <= 32'b00000000000000000000000000000000;
end

endmodule //Pool
